### ISSUE TITLE
한글폰트파일이 제대로 생성되지 않습니다.

### ISSUE THREAD

**Issue by sagneun** [yjjng11/Neural-fonts-webapp#1]
convert btn을 눌러서 .svg 파일을 생성하는 과정에서 다음과 같은 문제를 발견했습니다.
'The fontHeight should larger than 1000 or it will be converted into the wrong shape. Using the "normalize" and "fontHeight" options can solve the problem.'

var fontStream = svgicons2svgfont({
    fontName: 'myfont',
    fontHeight: 1001,
    normalize: true
});
위와 같은 추가 수정을 해서 fontHeight, normalize 문제는 나타나지 않았지만 font_ss.svg 파일에서 d="" 로 속성에 값이 제대로 들어가지 않습니다. npm install -g svgicons2svgfont 설치를 하고 command line에서 svgicons2svgfont --fontname=myfont -o svg_fonts/font_ss.svg svg/*.svg으로 실행시켰더니 d="M 104.5 33 Q ... Z " 와 같이 d 에 값이 들어간 것을 확인했습니다. 

svg2ttf 는 오픈되어있는 모듈을 사용하지 않고 Neural font 프로젝트에 있는 모듈을 사용해서 스크립트를 작성하고 실행했는데 myfont.ttf가 생성은 되지만 윈도우에서 미리보기로 myfont.ttf 를 확인했을 때 기대했던 글씨체는 없고 고딕체와 상당히 비슷한 글씨체들로만 표현이 됩니다. 

따라서 myfont.ttf 뿐만 아니라 font_ss.svg 또한 제대로 생성이 된 것인지 확인할 수 없습니다.

1) 해당 프로젝트를 개발하실 때 fontHeight, normalize 문제를 발견하셨나요? 발견 하셨다면, 어떻게 해결을 하셨나요?
2) ttf 파일을 실제 문서에 적용을 하는 과정에서 따로 처리를 해야하는 작업이 있나요?

**Comment by jinevening** [comment]
답변드립니다.

fontHeight, normalize 문제는 저희가 구현을 할 때 봤던 로그인데,  그 로그가 나온 채로 진행해도 폰트가 잘 생성 돼서 무시했던 것 같습니다.

ttf 파일이 잘 생성되었다면 따로 처리를 하실 필요가 없습니다. 예를 들어 ppt 에서 사용한다면 폰트를 고르는 곳에서 myfont 를 골라 사용하실 수 있어야 합니다. 말씀하신 시나리오에서는 기대와 다른 글씨체로 폰트가 만들어 졌다고 하셨는데 어느 부분이 문제인지 잘 가늠이 되지 않습니다. 단계별로 다음과 같이 문제점을 파악하시길 추천드립니다.

1. training이 잘 돼서 infer를 할 때 png 파일들이 잘 생성 되는지,
2. png 파일들이 vectorize 되어서 svg directory 아래에 svg 파일로 잘 생성 되는지, 
3. svg 파일들의 데이터가 svg font로 잘 묶였는지, 
4. 마지막으로 svg font 가 ttf 파일로 생성 될 때 문제가 발생하는지.

만약 png 파일들이 잘 생성되었는데 svg, ttf 생성 단계에서 문제가 발생한다면 svgicons2svgfont, svg2ttf 패키지의 issue 나 사용법을 참고하시면 도움이 되실 것 같습니다.

감사합니다.
