### ISSUE TITLE
validation 할 때 src와 dst가 같은 이유가 뭔가요?

### ISSUE THREAD

**Issue by Kim-dongeon** [yjjng11/Neural-fonts-webapp#2]
오픈소스를 보던 중 궁금한 점이 생겨서 질문남깁니다.

1. train할 때 source는 나눔고딕체이고 target은 손으로 쓴 글씨체가 되는게 맞나요?
build_model에서 real_B : 손으로 쓴 글씨 real_A : 나눔고딕체 인가요, 나눔고딕체에서 손글씨로 변할 수 있도록 특징을 추출하고 infer과정에서 나눔고딕체 글자 전체에 특징을 적용한다고 이해하는게 맞나요?

2. validation할 때 src,dst모두 나눔고딕체가 들어가는데 똑같은 폰트두개를 넣는 이유가 뭔가요? src부분에만 나눔고딕체를 넣고 dst부분은 백지로 만들어도 결과는 같은가요?

3. constant_loss를 왜 구하는지 궁금합니다. 왜 source를 인코딩한 것과, 생성된 폰트를 다시 인코딩하여서 loss를 구하나요... 어떤의미가 있을까요

4.글자 템플릿이 399자인데 혹시 399자를 선정한 기준같은것이 있을까요?
감사합니다.

**Comment by jinevening** [comment]
답변드립니다.

1. 맞습니다. 나눔고딕에서 타겟 폰트로 변형되는 방식으로 타겟폰트를 생성합니다.

2. Validation 용 데이터셋을 만드는 과정에서 그렇게 구현을 했습니다.

3. 두 데이터의 인코딩 결과가 비슷할것이라는 추측 때문입니다. 저희가 이용한 zi2zi 프로젝트의 블로그에 방문하시면 해당 내용에 대해 좀 더 자세히 설명 되어 있습니다.

4. 초성중성종성의 조합이 가장 골고루 퍼지도록 하면서 결과가 가장 잘 나오는 트레이닝셋을 경험적으로 골랐습니다.

감사합니다.
